---
sudo: required
dist: trusty
language: node_js

node_js:
  - 9

python:
  - 3.6.x

git:
  depth: false

addons:
  apt:
    packages:
      - imagemagick
      - graphicsmagick

install:
  - wget https://github.com/gohugoio/hugo/releases/download/v0.42/hugo_0.42_Linux-64bit.deb
  - sudo dpkg -i hugo*.deb
  - npm install
  - npm install --global gulp-cli
  - wget https://github.com/tdewolff/minify/releases/download/v2.3.4/minify_2.3.4_linux_amd64.tar.gz
  - mkdir ./tools
  - tar -xf minify_2.3.4_linux_amd64.tar.gz -C ./tools

script:
  - gulp build
  - ./tools/minify --html-keep-conditional-comments --html-keep-document-tags --html-keep-end-tags -r -o public/ -a public/
  - if [[ "$TRAVIS_TAG" != "" ]]; then mv ./public site_$TRAVIS_TAG; fi
  - if [[ "$TRAVIS_TAG" != "" ]]; then zip site_$TRAVIS_TAG.zip -r site_$TRAVIS_TAG; fi

deploy:
  - provider: releases
    api_key: $GITHUB_TOKEN
    skip_cleanup: true
    file: ./site_$TRAVIS_TAG.zip
    on:
      tags: true
