baseURL = "https://nats.io/"
languageCode = "en-us"
defaultLanguage = "en"
title = "NATS.io"

pygmentsCodeFences = "true"
pygmentsUseClasses = "true"
pygmentsStyle = "native"

[markup.goldmark.renderer]
unsafe = true

[taxonomies]
tag = "tags"
category = "categories"

[params]
tagline = "Cloud Native, Open Source, High-performance Messaging"
favicon = "favicon.ico"
font_awesome_version = "6.4.0"
leftNav = false
description = "NATS is a connective technology powering modern distributed systems, unifying Cloud, On-Premise, Edge, and IoT."
author = "The NATS Team"
title = "NATS.io"
url = "https://nats.io/"
SectionPagesMenu = "main"
noCategoryLink = true
githubBaseUrl = "https://github.com/nats-io/nats-site/edit/main/content"
images = ["/img/new_social_nats.png"]
description_long = """
NATS.io is a simple, secure, high-performance, open source messaging system for cloud native applications, IoT messaging, and microservice architectures.

Members of the [Synadia](https://synadia.com) team created and maintain the NATS and Streaming Servers, as well as clients written in Go, Java, JavaScript/TypeScript, Python, Ruby, C#, C, and NGINX. The community has also contributed a growing list of client libraries, including Arduino, Rust, Lua, PHP, Perl, and [more](https://nats.io/download).

Companies like MasterCard, Ericsson, HTC, Siemens, VMware, Pivotal, GE, and Baidu, among others, rely on the NATS.io messaging system for its highly performant, secure and resilient capabilities.
"""

[mediaTypes."text/netlify"]
delimiter = ""

[outputFormats.REDIRECTS]
mediaType = "text/netlify"
baseName = "_redirects"

[outputs]
home = [ "HTML", "REDIRECTS" ]

[[params.social]]
label = "Twitter"
icon = "twitter"
url = "https://twitter.com/nats_io"
color = "twitter-blue"

[[params.social]]
label = "GitHub"
icon = "github"
url = "https://github.com/nats-io"

[[params.social]]
label = "Slack"
icon = "slack"
url = "https://slack.nats.io"
color = "slack-purple"

[[params.social]]
label = "YouTube"
icon = "youtube"
url = "https://youtube.com/c/nats_messaging/videos"
color = "youtube-red"

[[params.social]]
label = "Stack Overflow"
icon = "stack-overflow"
url = "https://stackoverflow.com/questions/tagged/nats.io"
color = "stack-orange"

[params.logos]
navbar = "nats-horizontal-color.png"
navbar_home = "nats-icon-white.png"
hero = "nats-horizontal-color.png"
footer_dark = "nats-icon-color.png"
footer_light = "nats-icon-color.png"

[[params.fonts]]
name = "Source Sans Pro"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Roboto Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

# Features
[[languages.en.params.features]]
title = "Single Platform"
description = "Streaming, Key-Value, Object store, PubSub"
icon = "compress-arrows-alt"

[[languages.en.params.features]]
title = "Microservices"
description = "Services can live anywhere and are easily discoverable. Decentralized, zerotrust security"
icon = "cubes"

[[languages.en.params.features]]
title = "Multi-cloud to Edge"
description = "Connect all your applications and data. In the cloud, on premise, and at the edge."
icon = "users-cog"

[[menu.main]]
name = "About"
weight = 1
identifier = "about"
url = "/about/"

[[menu.main]]
name = "Download"
weight = 2
identifier = "download"
url = "/download/"

[[menu.main]]
name = "NATS"
weight = 1
identifier = "nats"
parent = "download"

[[menu.main]]
name = "Documentation"
weight = 3
identifier = "doc"
url = "https://docs.nats.io"

[[menu.main]]
name = "Getting Started With NATS"
weight = 1
parent = "doc"

[[menu.main]]
name = "Writing Applications"
weight = 2
parent = "doc"

[[menu.main]]
name = "Managing the Server"
weight = 3
parent = "doc"

[[menu.main]]
name = "NATS Internals"
weight = 4
parent = "doc"

[[menu.main]]
name = "Event Streaming"
weight = 5
parent = "doc"

[[menu.main]]
name = "Additional Documentation"
weight = 6
parent = "doc"

[[menu.main]]
name = "Blog"
weight = 5
identifier = "blog"
url = "/blog"

[[menu.main]]
name = "Support"
weight = 7
identifier = "support"
url = "/support"

[[menu.main]]
name = "Community"
weight = 6
identifier = "community"
url = "/community"

[[menu.main]]
name = "Privacy"
weight = 8
identifier = "privacy"
url = "/privacy"
