baseURL = "http://nats.io/"
languageCode = "en-us"
defaultLanguage = "en"
title = "NATS - Cloud Native, Open Source, High Performance Messaging"

pygmentsCodeFences = "true"
pygmentsUseClasses = "true"
pygmentsStyle = "native"

[params]
leftNav = false
description = "NATS is a high performance messaging system that acts as a distributed messaging queue for cloud native applications, IoT device messaging, and microservices architecture."
author = "The NATS team"
title = "NATS - Documentation"
SectionPagesMenu = "main"
noCategoryLink = true
githubBaseUrl = "https://github.com/nats-io/nats-site/edit/master/content"

[[menu.main]]
name = "About"
weight = 1
identifier = "about"
url = "/about"

[[menu.main]]
name = "Download"
weight = 2
identifier = "download"
url = "/download"

[[menu.main]]
name = "NATS"
weight = 1
identifier = "nats"
parent = "download"

[[menu.main]]
name = "Server"
weight = 1
identifier = "nats-server"
parent = "nats"

[[menu.main]]
name = "Synadia Supported Clients"
weight = 2
identifier = "nats-clients"
parent = "nats"

[[menu.main]]
name = "Community Clients"
weight = 3
identifier = "nats-community"
parent = "nats"

[[menu.main]]
name = "NATS Streaming"
weight = 0
identifier = "nats-streaming"
parent = "download"

[[menu.main]]
name = "Server"
weight = 1
identifier = "streaming-server"
parent = "nats-streaming"

[[menu.main]]
name = "Synadia Supported Clients"
weight = 2
identifier = "streaming-clients"
parent = "nats-streaming"

[[menu.main]]
name = "Community Clients"
weight = 3
identifier = "streaming-community"
parent = "nats-streaming"

[[menu.main]]
name = "Documentation"
weight = 3
identifier = "doc"
url = "/documentation"

[[menu.main]]
name = "Getting Started With NATS"
weight = 1
parent = "doc"

[[menu.main]]
name = "Writing Applications"
weight = 2
parent = "doc"

[[menu.main]]
name = "Managing the Server"
weight = 3
parent = "doc"

[[menu.main]]
name = "NATS Internals"
weight = 4
parent = "doc"

[[menu.main]]
name = "Event Streaming"
weight = 5
parent = "doc"

[[menu.main]]
name = "Additional Documentation"
weight = 6
parent = "doc"

[[menu.main]]
name = "Support"
weight = 4
identifier = "support"
url = "/support"

[[menu.main]]
name = "Community"
weight = 5
identifier = "community"
url = "/community"

[[menu.main]]
name = "Blog"
weight = 6
identifier = "blog"
url = "/blog"

[[menu.main]]
name = "Privacy"
weight = 7
identifier = "privacy"
url = "/privacy"