[build]
publish = "public"
command = "make netlify-production-build"

[build.environment]
HUGO_VERSION = "0.73.0"

[context.deploy-preview]
command = "make netlify-preview-build"

[context.branch-deploy]
command = "make netlify-preview-build"
